### ISSUE TITLE
What if I wanted to add a file `__init__.py` to the template folder?

### ISSUE THREAD

**Issue by korayal** [sethyuan/fgen#1]
So, I need to add this file to each generated project folder. Is there a way to not rename files that are not in the list of keywords?

Additionally,
If we place a file to folder `__val1__/test/__val2__.js` it fails to generate since we first need the `val1` folder to be created **before** `val2.js`

**Comment by sethyuan** [comment]
Hi @korayal,

Regarding the second case `__val1__/test/__val2__.js`, this bug is been fixed, an new version is published to npm. The cause was a bad RegEx, not generation order.

About generating `__init__.py`, there is a workaround, provide a key `init` in your context with the value `__init__`.

**Comment by korayal** [comment]
I was creating those files via fs library after generator finished it's job. I think your workaround is simpler. thanks for that. 

But I would still vote for not renaming files that are not provided as a key :)

**Comment by sethyuan** [comment]
@korayal, it makes sense. I published a new version with the behavior you described. I'll close this issue once you verify it.

**Comment by korayal** [comment]
hey, this issue was lost among my emails. just tested it and it works alright. thank you
